"""The investigation as one self-contained HTML file — the thing you hand over.

HLD §13.9 orders the front ends: CLI **first**, this report **alongside it**, the
App page after, MCP last. The MCP front end got built first and this one — ordered
ahead of it — was skipped. `scan` and `oee measure` could both put their answer on
paper; the investigation, which is what an integrator actually hands to a plant,
could not.

**Where this deliberately parts company with the OEE report.** `oee measure
--report` *refuses* to write a file when the measurement was refused, and it is
right to: an OEE report is a number, so a file existing at all asserts that the
number was measured. An investigation report is the opposite. Its content is *how
far this got and what each remaining step needs* — so the blocked case is the one
most worth forwarding, and for a site nobody has instrumented yet it is the entire
deliverable.

What it must never do is let a blocked investigation LOOK finished. Hence the one
rule the section order encodes, the same rule the OEE report follows by putting
coverage before the number: **the headline is the walk, never a conclusion.** A
step's own words never appear above it.

The two-way distinction from §9.4 is carried all the way onto the page, because
losing it here would waste somebody's afternoon: a gap you have not supplied sends
a person to `config.yaml`, and a gap the product cannot accept sends them to the
issue tracker. Rendered identically, half of them go looking for a setting that
does not exist.

[PURE] No I/O, no clock. ``generated_at`` comes from the caller, so the same
payload renders the same bytes twice — two investigations of one incident have to
be diffable.
"""

from __future__ import annotations

from typing import Any

from iaiops.core.report.html import document, escape, kv

#: The states a live step can be in, mapped to a badge colour. `refused` and
#: `not_possible` are deliberately different colours as well as different words.
_LIVE_TONE = {
    "done": "ok",
    "pending": "none",
    "refused": "partial",
    "not_possible": "aborted",
}
_PLAN_TONE = {"ready": "ok", "degraded": "partial", "blocked": "aborted"}

EN: dict[str, Any] = {
    "plan_title": "Investigation readiness",
    "live_title": "Investigation",
    "generated": "Generated",
    "site": "Site",
    "endpoint": "Endpoint",
    "asset": "Asset",
    "window": "Window",
    "opened": "Opened",
    "id": "Investigation",
    "reach_h": "How far this gets",
    "reach_plan": "the walk reached step {n} of {total} before a step could not be satisfied",
    "reach_live": "the walk reached step {n} of {total}",
    "reach_none": "the walk stops before step 1",
    "reach_all": "all {total} steps were walked",
    "steps_h": "The eight steps",
    "step": "Step",
    "state": "State",
    "found": "What it found",
    "gives": "What it gives you",
    "gaps_h": "What to supply next",
    "gaps_lead": (
        "Ranked by where the walk stops. Supplying the first one is what moves "
        "the investigation forward; the rest are only reachable after it."
    ),
    "gaps_none": "Nothing is missing — every step could be satisfied here.",
    "inexpressible": "this product offers no way to supply it yet",
    "fix": "Next step",
    "not_claimed_h": "What this does not claim",
    "not_claimed": [
        "A step that was not walked has no verdict. Absence of a finding is not a "
        "finding of absence.",
        "Nothing here was guessed. Which tag means what is process knowledge, and a "
        "plausible guess produces plausible wrong answers.",
        "A cause is never raised to confirmed by this page. Confirmation comes from "
        "a measurement, a reproduction, or a person.",
        "Nothing was written to any device. Every line came from reading and from "
        "what somebody declared.",
    ],
    "footer": (
        "Generated by iaiops. Self-contained: this file loads nothing and runs "
        "nothing. Every value the site supplied is escaped."
    ),
}

ZH: dict[str, Any] = {
    "plan_title": "调查就绪度",
    "live_title": "调查",
    "generated": "生成于",
    "site": "站点",
    "endpoint": "端点",
    "asset": "设备 / 产线",
    "window": "时间窗",
    "opened": "开启于",
    "id": "调查编号",
    "reach_h": "这次能走到哪里",
    "reach_plan": "走到第 {n} 步(共 {total} 步),再往后有一步无法满足",
    "reach_live": "走到第 {n} 步(共 {total} 步)",
    "reach_none": "第 1 步就走不下去",
    "reach_all": "{total} 步全部走完",
    "steps_h": "八个步骤",
    "step": "步骤",
    "state": "状态",
    "found": "查到了什么",
    "gives": "它给你什么",
    "gaps_h": "接下来要补什么",
    "gaps_lead": "按走到哪停下来排序。补上第一条才推得动;后面几条要等它补上才轮得到。",
    "gaps_none": "没有缺口 —— 每一步在这个站点都能满足。",
    "inexpressible": "本产品尚无办法接收这一项",
    "fix": "下一步",
    "not_claimed_h": "这份报告不声称什么",
    "not_claimed": [
        "没走到的步骤没有结论。查不到不等于不存在。",
        "这里没有任何一处是猜的。哪个位号是什么意思属于工艺知识,猜得像样只会得出像样的错答案。",
        "本页绝不把任何原因升级为「已确认」。确认来自一次测量、一次复现,或一个人。",
        "没有向任何设备写入。每一行都来自读取,以及某个人的声明。",
    ],
    "footer": (
        "由 iaiops 生成。自包含:本文件不加载任何东西,也不运行任何东西。站点提供的每个值都已转义。"
    ),
}

LANGUAGES = {"en": EN, "zh": ZH}

_EXTRA_CSS = """
.reach { font-size:2.4rem; font-weight:800; line-height:1.1; margin:.3rem 0 .1rem; }
.reach-sub { color:var(--muted); font-size:.87rem; margin:0 0 1.25rem; }
.strip { display:flex; gap:.35rem; list-style:none; padding:0; margin:.4rem 0 1.25rem;
         flex-wrap:wrap; }
.strip li { flex:1 1 60px; min-width:56px; border-radius:6px; padding:.4rem .3rem;
            text-align:center; font-size:.7rem; font-weight:700;
            border:1px solid var(--line); background:var(--card); color:var(--muted); }
.strip li.ok { border-color:var(--ok); color:var(--ok); }
.strip li.partial { border-color:var(--warn); color:var(--warn); }
.strip li.aborted { border-color:var(--bad); color:var(--bad); }
td.wide { white-space:normal; min-width:16rem; }
ul.gaps { list-style:none; padding:0; margin:.5rem 0 0; }
ul.gaps li { padding:.55rem 0; border-bottom:1px solid var(--line); font-size:.88rem; }
ul.gaps li:last-child { border-bottom:none; }
.gap-fix { color:var(--muted); font-size:.83rem; display:block; margin-top:.2rem; }
.gap-none { color:var(--warn); font-weight:600; }
"""


def _strings(lang: str) -> dict:
    """Refuse an unknown language rather than falling back to English.

    A silent fallback is how a Chinese page ends up half English, and the strings
    added late are the honesty caveats — the ones that must not quietly vanish for
    half the readers.
    """
    key = (lang or "").strip().lower()
    if key not in LANGUAGES:
        raise ValueError(f"Unknown report language {lang!r}. Available: {', '.join(LANGUAGES)}.")
    return LANGUAGES[key]


def _header(t: dict, *, title: str, tiles: list[str], generated_at: str) -> str:
    cells = "".join(tiles + [kv(t["generated"], generated_at)])
    return "<h1>" + escape(title) + '</h1><dl class="kv grid">' + cells + "</dl>"


def _reach(t: dict, *, reached: int, total: int, tones: list[str], live: bool) -> str:
    """The walk, and nothing else. This is the only thing allowed above the steps.

    A renderer that promoted the last step's text here would read as a finding,
    and a blocked investigation would look finished.
    """
    if reached <= 0:
        sub = t["reach_none"]
    elif reached >= total:
        sub = t["reach_all"].format(total=total)
    else:
        sub = t["reach_live" if live else "reach_plan"].format(n=reached, total=total)
    boxes = "".join(
        '<li class="' + escape(tone) + '">' + str(i + 1) + "</li>"
        for i, tone in enumerate(tones[:total])
    )
    return (
        "<h2>" + escape(t["reach_h"]) + "</h2>"
        '<p class="reach">' + str(reached) + " / " + str(total) + "</p>"
        '<p class="reach-sub">' + escape(sub) + "</p>"
        '<ol class="strip">' + boxes + "</ol>"
    )


def _badge(state: str, tone: str) -> str:
    """The raw state rides in the class, so ``refused`` and ``not_possible`` stay
    two distinct words on the page rather than two shades of "not done"."""
    return (
        '<span class="badge '
        + escape(tone)
        + " "
        + escape(state)
        + '">'
        + escape(state)
        + "</span>"
    )


def _steps_table(t: dict, rows: str, third: str) -> str:
    return (
        "<h2>" + escape(t["steps_h"]) + "</h2>"
        '<div class="scroll"><table><thead><tr>'
        "<th>#</th><th>" + escape(t["step"]) + "</th><th>" + escape(t["state"]) + "</th>"
        "<th>" + escape(third) + "</th>"
        "</tr></thead><tbody>" + rows + "</tbody></table></div>"
    )


def _row(number: Any, label: str, badge: str, last: str) -> str:
    return (
        "<tr><td>" + escape(number) + "</td>"
        '<td class="wide">' + escape(label) + "</td>"
        "<td>" + badge + "</td>"
        '<td class="wide">' + escape(last) + "</td></tr>"
    )


def _plan_steps(t: dict, steps: list[dict]) -> str:
    rows = []
    for step in steps:
        status = str(step.get("status", ""))
        rows.append(
            _row(
                step.get("number", ""),
                str(step.get("label", "")),
                _badge(status, _PLAN_TONE.get(status, "none")),
                str(step.get("value", "")),
            )
        )
    return _steps_table(t, "".join(rows), t["gives"])


def _live_steps(t: dict, steps: list[dict]) -> str:
    rows = []
    for step in steps:
        state = str(step.get("state", ""))
        rows.append(
            _row(
                step.get("number", ""),
                str(step.get("label", "")),
                _badge(state, _LIVE_TONE.get(state, "none")),
                str(step.get("summary", "")),
            )
        )
    return _steps_table(t, "".join(rows), t["found"])


def _gap_key(req: dict) -> tuple[str, str]:
    """Group by the ACTION where there is one, since that is what a reader does.

    An inexpressible requirement has no fix by definition, so it groups by its own
    key — otherwise every inexpressible gap in a report would collapse into one.
    """
    fix = str(req.get("fix") or "").strip()
    if fix and not req.get("not_yet_expressible"):
        return ("fix", fix)
    return ("key", str(req.get("key") or req.get("label", "")))


def _gap_item(t: dict, steps_blocked: list, req: dict) -> str:
    label = escape(req.get("label", ""))
    detail = escape(req.get("detail", ""))
    where = ", ".join(escape(n) for n in steps_blocked)
    head = "<b>" + where + ". " + label + "</b>"
    if detail:
        head += " — " + detail
    if req.get("not_yet_expressible"):
        tail = '<span class="gap-fix gap-none">→ ' + escape(t["inexpressible"]) + "</span>"
    elif req.get("fix"):
        tail = '<span class="gap-fix">' + escape(t["fix"]) + ": " + escape(req["fix"]) + "</span>"
    else:
        tail = ""
    return "<li>" + head + tail + "</li>"


def _gaps(t: dict, steps: list[dict]) -> str:
    """Every unmet requirement ONCE, in walk order, saying which steps it holds up.

    Deduped by ACTION, not by requirement key. Deduping by key was the obvious
    move and it changed nothing: on a bare site four steps want four differently
    named things — "collected samples", "samples to check", "a sampled series",
    "evidence to rank" — that are all supplied by one `collect run`. Four keys,
    one action, four lines on a page whose own lead says it is ranked by where the
    walk stops. Four copies of one action read as four problems.

    Requirements with no fix (the inexpressible ones) fall back to their key, since
    they have no action to group by — by definition.

    The inexpressible marker is emitted HERE and nowhere else — not in a legend,
    not in the honesty section — so a report with no inexpressible gap does not
    carry the phrase at all. A marker that is always present marks nothing.
    """
    seen: dict[tuple[str, str], dict] = {}
    for step in steps:
        for req in step.get("requirements") or []:
            if req.get("met"):
                continue
            entry = seen.setdefault(_gap_key(req), {"req": req, "steps": []})
            if step.get("number", "") not in entry["steps"]:
                entry["steps"].append(step.get("number", ""))
    items = [_gap_item(t, e["steps"], e["req"]) for e in seen.values()]
    if not items:
        return (
            "<h2>" + escape(t["gaps_h"]) + "</h2>"
            '<p class="empty">' + escape(t["gaps_none"]) + "</p>"
        )
    return (
        "<h2>" + escape(t["gaps_h"]) + "</h2>"
        '<p class="sub">' + escape(t["gaps_lead"]) + "</p>"
        '<ul class="gaps">' + "".join(items) + "</ul>"
    )


def _not_claimed(t: dict) -> str:
    lines = "".join("<li>" + escape(x) + "</li>" for x in t["not_claimed"])
    return "<h2>" + escape(t["not_claimed_h"]) + '</h2><ul class="notes">' + lines + "</ul>"


def render_plan_report(payload: dict, *, lang: str = "en", generated_at: str = "") -> str:
    """[PURE] One self-contained file from ``iaiops investigate plan --json``.

    This is the report for a site that has not been instrumented yet: it says how
    far an investigation could get here and what each remaining step is waiting
    for. That it renders at all when nothing is reachable is the point — unlike
    the OEE report, the gaps are the deliverable.
    """
    t = _strings(lang)
    steps = list(payload.get("steps") or [])
    reached = int(payload.get("reachable_through", 0) or 0)
    tones = [_PLAN_TONE.get(str(s.get("status", "")), "none") for s in steps]
    body = "".join(
        [
            _header(
                t,
                title=t["plan_title"],
                tiles=[kv(t["site"], payload.get("site", ""))],
                generated_at=generated_at,
            ),
            _reach(
                t,
                reached=reached,
                total=int(payload.get("total_steps", len(steps)) or len(steps)),
                tones=tones,
                live=False,
            ),
            _plan_steps(t, steps),
            _gaps(t, steps),
            _not_claimed(t),
        ]
    )
    return document(
        title=f"{t['plan_title']} — {payload.get('site', '')}",
        body=body,
        footer=escape(t["footer"]),
        lang=lang,
        extra_css=_EXTRA_CSS,
    )


def render_live_report(payload: dict, *, lang: str = "en", generated_at: str = "") -> str:
    """[PURE] One self-contained file from ``iaiops investigate open/show --json``.

    The same eight steps over a real past window. A step that was not walked has
    no verdict here, and the page says so rather than leaving a blank that reads
    as "nothing was wrong".
    """
    t = _strings(lang)
    steps = list(payload.get("steps") or [])
    scope = payload.get("scope") or {}
    window = f"{scope.get('start', '')} → {scope.get('end', '')}"
    tones = [_LIVE_TONE.get(str(s.get("state", "")), "none") for s in steps]
    body = "".join(
        [
            _header(
                t,
                title=t["live_title"],
                tiles=[
                    kv(t["endpoint"], scope.get("endpoint", "")),
                    kv(t["asset"], scope.get("asset", "")),
                    kv(t["site"], payload.get("site", "")),
                    kv(t["window"], window),
                    kv(t["id"], payload.get("id", "")),
                    kv(t["opened"], payload.get("opened_at", "")),
                ],
                generated_at=generated_at,
            ),
            _reach(
                t,
                reached=int(payload.get("reached", 0) or 0),
                total=int(payload.get("total_steps", len(steps)) or len(steps)),
                tones=tones,
                live=True,
            ),
            _live_steps(t, steps),
            _not_claimed(t),
        ]
    )
    return document(
        title=f"{t['live_title']} — {scope.get('endpoint', '') or payload.get('site', '')}",
        body=body,
        footer=escape(t["footer"]),
        lang=lang,
        extra_css=_EXTRA_CSS,
    )


__all__ = ["render_plan_report", "render_live_report", "EN", "ZH", "LANGUAGES"]
