"""The report's words, in both languages it ships in.

One dict per language, the SAME keys in both. A test asserts the key sets are
equal, because the failure mode without it is silent: a missed translation falls
back to English and lands in the middle of a Chinese page, and the strings most
likely to be added late are the honesty caveats — exactly the ones that must not
quietly disappear for half the readers.

Nothing here is formatted with the site's own data; every value the site supplied
is escaped at the point it is rendered, not here.
"""

from __future__ import annotations

EN: dict[str, str] = {
    "title": "OEE",
    "generated": "Generated",
    "site": "Site",
    "endpoint": "Endpoint",
    "tag": "Run-state tag",
    # ── section 1: what the measurement could see ────────────────────────────
    "seen_h": "What this measurement could see",
    "seen_lead": (
        "Read this before the number. Everything below is measured over the window "
        "the collector could actually observe — not over the shift, and not over "
        "the plant's production schedule, which this tool has not been given."
    ),
    "window": "Window",
    "duration": "Observed",
    "coverage": "Coverage",
    "blind": "Blind",
    "samples": "Samples",
    "cadence": "Actual cadence",
    "stops": "Stoppages",
    "minor_stops": "Of those, minor",
    "not_claimed_h": "What this does not claim",
    "not_claimed": [
        "Blind time is excluded, not counted as downtime — a dropped connection "
        "is not a stopped line.",
        "A stoppage shorter than about twice the sample cadence is invisible here, "
        "exactly as it is to a manual tally.",
        "Planned time means the time that was OBSERVED. No production schedule was supplied.",
        "Nothing was written to any device. Every number came from reading.",
    ],
    # ── section 2: the figure ────────────────────────────────────────────────
    "oee_h": "OEE",
    "availability": "Availability",
    "performance": "Performance",
    "quality": "Quality",
    "oee_formula": "Availability × Performance × Quality",
    "oee_partial": (
        "No single OEE figure: {missing} could not be measured. The factors that "
        "ARE measured are reported above; multiplying in a guess would produce a "
        "number that looks whole and is not."
    ),
    "not_measurable": "not measurable",
    "produced": "Parts counted",
    "discontinuities": "Counter discontinuities",
    "unobserved_steps": "Increments skipped as blind",
    # ── section 3: the losses ────────────────────────────────────────────────
    "losses_h": "Where the time went",
    "fully_productive": "Fully productive",
    "loss": "Loss",
    "bucket": "Bucket",
    "time": "Time",
    "share": "Share of observed time",
    "provenance": "Basis",
    "classified": "measured split",
    "unclassified": "residual — no split supplied",
    "largest": "Largest loss",
    "largest_note": "the one worth attacking first",
    "loss_breakdown": "Breakdown",
    "loss_setup": "Setup / changeover",
    "loss_minor_stops": "Minor stops",
    "loss_speed_loss": "Speed loss",
    "loss_startup_rejects": "Start-up rejects",
    "loss_production_rejects": "Production rejects",
    "bucket_availability": "Availability",
    "bucket_performance": "Performance",
    "bucket_quality": "Quality",
    # ── section 4: against the site's own figure ─────────────────────────────
    "compare_h": "Against the figure this site keeps",
    "reported": "Reported",
    "measured": "Measured",
    "gap": "Gap",
    "points": "points",
    # ── section 5: prerequisites ─────────────────────────────────────────────
    "needs_h": "What these numbers required, and what is still missing",
    "needs_lead": (
        "Every figure above has a prerequisite somebody had to supply. A demo that "
        "hides this row fails on first contact with a real site, so here it is."
    ),
    "needs_supplied": "Supplied",
    "needs_missing": "Still missing",
    "need_run_state": (
        "A tag declared `role: run_state` with `running_when:` — which value means producing"
    ),
    "need_total_count": "A tag declared `role: total_count` — the production counter",
    "need_good_count": "A tag declared `role: good_count` — without it Quality cannot be measured",
    "need_cycle": "`ideal_cycle_time_s:` on the endpoint — the design cycle",
    "need_collection": "A collection run long enough to cover the window",
    "nothing_missing": "Nothing. Every input these figures need was declared.",
    # ── appendix + footer ────────────────────────────────────────────────────
    "appendix_h": "Appendix — the numbers behind the page",
    "appendix_lead": "Everything rendered above, verbatim, so any figure can be checked.",
    "footer": (
        "Generated by iaiops. This file is self-contained: it loads no fonts, "
        "scripts, styles or images from anywhere, and makes no network request "
        "when opened."
    ),
    "note_h": "About these numbers",
}

ZH: dict[str, str] = {
    "title": "OEE 设备综合效率",
    "generated": "生成时间",
    "site": "站点",
    "endpoint": "端点",
    "tag": "运行状态位号",
    "seen_h": "这次测量看见了什么",
    "seen_lead": (
        "先看这一节,再看数字。下面所有结果都只覆盖采集器**真正看得见**的那段时间 —— "
        "不是整个班次,也不是工厂的排产计划(这个工具没有拿到排产计划)。"
    ),
    "window": "窗口",
    "duration": "已观测",
    "coverage": "覆盖率",
    "blind": "盲区",
    "samples": "样本数",
    "cadence": "实际节拍",
    "stops": "停机次数",
    "minor_stops": "其中微停",
    "not_claimed_h": "这份报告不主张什么",
    "not_claimed": [
        "盲区时间被**排除**,没有算成停机 —— 断连不等于产线停了。",
        "短于约两倍采样节拍的停机在这里看不见,这一点和人工记录一样。",
        "「计划时间」在这里指**被观测到的时间**。没有任何排产计划被提供。",
        "全程没有向任何设备写入。每个数字都来自读取。",
    ],
    "oee_h": "OEE",
    "availability": "可用率",
    "performance": "性能",
    "quality": "质量",
    "oee_formula": "可用率 × 性能 × 质量",
    "oee_partial": (
        "没有单一 OEE 数字:{missing} 无法测量。上面报告的是**确实测到**的因子;"
        "把猜测乘进去会得到一个看起来完整、实际不是的数。"
    ),
    "not_measurable": "无法测量",
    "produced": "计数产量",
    "discontinuities": "计数器断点",
    "unobserved_steps": "因盲区跳过的增量",
    "losses_h": "时间去哪了",
    "fully_productive": "完全有效产出",
    "loss": "损失",
    "bucket": "归属",
    "time": "时长",
    "share": "占已观测时间",
    "provenance": "依据",
    "classified": "有实测拆分",
    "unclassified": "残差 —— 未提供拆分",
    "largest": "最大损失",
    "largest_note": "先打这一个",
    "loss_breakdown": "故障停机",
    "loss_setup": "换型 / 调整",
    "loss_minor_stops": "微停",
    "loss_speed_loss": "速度损失",
    "loss_startup_rejects": "开机废品",
    "loss_production_rejects": "生产废品",
    "bucket_availability": "可用率",
    "bucket_performance": "性能",
    "bucket_quality": "质量",
    "compare_h": "对照厂里自己在用的数字",
    "reported": "厂里的数",
    "measured": "实测",
    "gap": "差距",
    "points": "个百分点",
    "needs_h": "这些数字要求了什么、还差什么",
    "needs_lead": (
        "上面每一个数字背后都有一个**得有人提供**的前置条件。一份把这一行藏起来的 demo,"
        "在第一次面对真实工厂时就会崩 —— 所以把它放在这里。"
    ),
    "needs_supplied": "已提供",
    "needs_missing": "仍缺少",
    "need_run_state": "一个声明了 `role: run_state` 和 `running_when:` 的位号 —— 哪个值代表在生产",
    "need_total_count": "一个声明了 `role: total_count` 的位号 —— 产量计数器",
    "need_good_count": "一个声明了 `role: good_count` 的位号 —— 没有它就测不出质量",
    "need_cycle": "端点上的 `ideal_cycle_time_s:` —— 设计节拍",
    "need_collection": "一次足够覆盖该窗口的采集",
    "nothing_missing": "没有。这些数字需要的输入都已声明。",
    "appendix_h": "附录 —— 页面背后的原始数字",
    "appendix_lead": "上面渲染的全部内容,原样附上,任何一个数都可以自己核。",
    "footer": (
        "由 iaiops 生成。本文件自包含:不从任何地方加载字体、脚本、样式或图片,"
        "打开时不发起任何网络请求。"
    ),
    "note_h": "关于这些数字",
}

LANGUAGES = {"en": EN, "zh": ZH}


def strings(lang: str) -> dict:
    """The table for ``lang``, refusing an unknown one rather than falling back.

    A silent fallback to English is how a Chinese report ends up half English —
    and the reader has no way to tell a translation gap from a deliberate term.
    """
    key = (lang or "").strip().lower()
    if key not in LANGUAGES:
        raise ValueError(f"Unknown report language {lang!r}. Available: {', '.join(LANGUAGES)}.")
    return LANGUAGES[key]


__all__ = ["EN", "ZH", "LANGUAGES", "strings"]
