"""The point-list confirmation page — the App front end, as one static file.

HLD §13.9 orders the App page after the CLI and the report, and justifies it
narrowly: it exists for the steps where a person must go **row by row and tick**
— point-list confirmation, timeline review — where a table beats command-line
question-and-answer. It is not a dashboard.

**Why a file and not a served app.** A localhost server inside an OT box has to
answer which address it binds, who authenticates, and how the firewall is opened.
Worse, every declaration in this product requires ``--by``, and a page with no
identity cannot answer "who ticked this" — the one thing this step exists to
record. The file sidesteps all of it: it opens on the laptop already in the plant
office, and the CSV it produces goes through ``iaiops tags apply``, which is
where the author is supplied and where the refusals live.

**It re-implements no refusal.** ``run_state`` needing ``running_when``, a ref
having to be monitored, a role claimed twice — reproducing any of those in
JavaScript is how they drift from the ones that actually gate the config, and a
page that says "looks fine" while ``apply`` refuses is worse than no page. The
page collects; ``apply`` judges. The role options come from ``TagRole.ALL`` at
render time for the same reason: a hand-written list is how a fifth role appears
on a page and is then rejected with no explanation.

Unlike the investigation and OEE reports this page **does** ship script — it is a
form. What stays true is the property that matters in a plant: it makes **no
network request**, and its data is embedded, not fetched.

[PURE] No I/O, no clock. ``generated_at`` is the caller's.
"""

from __future__ import annotations

import json
from typing import Any

from iaiops.core.report.html import escape
from iaiops.core.runtime.tag_sheet import SHEET_COLUMNS, sheet_rows

EN: dict[str, Any] = {
    "title": "Confirm what each tag means",
    "lead": (
        "One row per monitored tag. Set the role for the few that carry one, then "
        "download the sheet and hand it to `iaiops tags apply`."
    ),
    "empty_h": "Nothing to confirm yet",
    "empty": (
        "No endpoint declares any monitored tag. Find devices first with "
        "`iaiops scan run --targets <cidr>`, then add endpoints and their tags "
        "with `iaiops init`."
    ),
    "endpoint": "Endpoint",
    "ref": "Tag",
    "label": "Label",
    "declared": "Already declared",
    "role": "Role",
    "running_when": "running_when",
    "running_hint": "for run_state: which value means producing",
    "none": "— not one of these —",
    "download": "Download sheet (CSV)",
    "copy_h": "Or copy the sheet",
    "next_h": "What happens next",
    "next": [
        "Nothing is decided here. This page collects; `iaiops tags apply "
        "sheet.csv --by <you>` checks it and prints the exact config.yaml edit.",
        "Nothing is pre-selected, including next to a tag whose name looks like a "
        "role. A name is not a declaration, and a wrong production counter yields "
        "a plausible OEE — worse than an error.",
        "A run_state tag also needs `running_when` — which value means the line is "
        "producing. `apply` refuses one without it.",
        "This file loaded nothing and sends nothing. It works with the network cable out.",
    ],
    "footer": "Generated by iaiops. Self-contained: nothing is loaded and nothing is sent.",
}

ZH: dict[str, Any] = {
    "title": "确认每个位号的含义",
    "lead": "每个被监控的位号一行。给带角色的那几个选上,然后下载表交给 `iaiops tags apply`。",
    "empty_h": "还没有可确认的东西",
    "empty": (
        "没有任何端点声明了被监控的位号。先找设备:`iaiops scan run --targets <cidr>`,"
        "再加端点和位号:`iaiops init`。"
    ),
    "endpoint": "端点",
    "ref": "位号",
    "label": "名称",
    "declared": "已声明",
    "role": "角色",
    "running_when": "running_when",
    "running_hint": "run_state 专用:哪个值代表在生产",
    "none": "— 都不是 —",
    "download": "下载表格(CSV)",
    "copy_h": "或者直接复制",
    "next_h": "接下来会发生什么",
    "next": [
        "这一页不决定任何事。它只负责收集;`iaiops tags apply sheet.csv --by <你>` "
        "负责校验,并打印出要贴进 config.yaml 的那几行。",
        "没有任何一项是预选的 —— 哪怕位号名字看起来就是某个角色。名字不是声明,"
        "选错产量计数器会得出一个看着合理的 OEE,比报错更糟。",
        "run_state 位号还需要 `running_when` —— 哪个值代表产线在生产。缺了 `apply` 会拒绝。",
        "本文件没有加载任何东西,也不向外发送任何东西。拔了网线照样用。",
    ],
    "footer": "由 iaiops 生成。自包含:不加载任何东西,也不发送任何东西。",
}

LANGUAGES = {"en": EN, "zh": ZH}

__all__ = ["render_tag_page", "EN", "ZH", "LANGUAGES"]

_EXTRA_CSS = """
select, input[type=text] { width:100%; padding:.3rem .4rem; border:1px solid var(--line);
  border-radius:5px; background:var(--card); color:var(--fg); font-size:.83rem; }
td.field { min-width:11rem; }
.actions { display:flex; gap:.6rem; align-items:center; margin:1.25rem 0 .5rem; flex-wrap:wrap; }
button { padding:.5rem .9rem; border-radius:6px; border:1px solid var(--accent);
  background:var(--card); color:var(--accent); font-weight:700; font-size:.85rem;
  cursor:pointer; }
button:hover { background:var(--code); }
textarea { width:100%; min-height:9rem; padding:.6rem; border:1px solid var(--line);
  border-radius:6px; background:var(--code); color:var(--fg); font-size:.75rem;
  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; }
.hint { color:var(--muted); font-size:.75rem; }
"""

# The page never decides anything, so the script only reads the controls and
# joins them into the same columns the CSV exporter uses. No rule lives here.
_JS = """
(function () {
  function quote(v) {
    var t = String(v == null ? '' : v);
    return /[",\\n]/.test(t) ? '"' + t.replace(/"/g, '""') + '"' : t;
  }
  function build() {
    var out = [SHEET.columns.join(',')];
    SHEET.rows.forEach(function (row, i) {
      var role = document.getElementById('role-' + i);
      var running = document.getElementById('run-' + i);
      // Driven by SHEET.columns rather than a hardcoded field order: pytest
      // never runs this script, so a reordering of SHEET_COLUMNS would have
      // shifted every value one column to the right with nothing to catch it.
      var live = { role: role ? role.value : '', running_when: running ? running.value : '' };
      out.push(SHEET.columns.map(function (name) {
        return quote(name in live ? live[name] : row[name]);
      }).join(','));
    });
    return out.join('\\n') + '\\n';
  }
  var area = document.getElementById('csv');
  function refresh() { if (area) { area.value = build(); } }
  document.addEventListener('change', refresh);
  document.addEventListener('input', refresh);
  refresh();
  var button = document.getElementById('download');
  if (button) {
    button.addEventListener('click', function () {
      var blob = new Blob([build()], { type: 'text/csv' });
      var link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = 'sheet.csv';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(link.href);
    });
  }
})();
"""


def _ref(tag: Any) -> str:
    value = getattr(tag, "ref", None)
    if value is None and isinstance(tag, dict):
        value = tag.get("ref")
    return str(value or "")


def _strings(lang: str) -> dict:
    key = (lang or "").strip().lower()
    if key not in LANGUAGES:
        raise ValueError(f"Unknown page language {lang!r}. Available: {', '.join(LANGUAGES)}.")
    return LANGUAGES[key]


def _embed(payload: dict) -> str:
    """Serialise for a ``<script>`` block.

    The escaping context here is JavaScript, not HTML text — a different trap
    from the reports. A tag label containing ``</script>`` would end the block
    early and turn everything after it into markup, so every ``<`` becomes
    ``\\u003c``: still valid JSON, still the same string once parsed, and no
    longer able to close the element.
    """
    return json.dumps(payload, ensure_ascii=False).replace("<", "\\u003c")


def _declared(row: dict[str, str], declared_running: dict[tuple[str, str], str]) -> str:
    """What config already says, as read-only context — role AND running_when.

    Both belong here rather than in the editable cells. Echoing the existing
    ``running_when`` into its input while leaving ``role`` blank was inconsistent
    in a way that bit: changing the role to a counter then got refused over a
    field the person never touched.
    """
    role = row["declared_role"]
    running = declared_running.get((row["endpoint"], row["ref"]), "")
    if role and running:
        return f"{role} (running_when: {running})"
    return role


def _row(
    t: dict,
    index: int,
    row: dict[str, str],
    roles: tuple[str, ...],
    declared_running: dict[tuple[str, str], str],
) -> str:
    options = "".join(f'<option value="{escape(role)}">{escape(role)}</option>' for role in roles)
    return (
        "<tr>"
        f"<td>{escape(row['endpoint'])}</td>"
        f'<td class="mono">{escape(row["ref"])}</td>'
        f"<td>{escape(row['label'])}</td>"
        f"<td>{escape(_declared(row, declared_running))}</td>"
        f'<td class="field"><select id="role-{index}">'
        f'<option value="">{escape(t["none"])}</option>{options}</select></td>'
        f'<td class="field"><input type="text" id="run-{index}" '
        f'value="" placeholder="{escape(t["running_hint"])}">'
        "</td>"
        "</tr>"
    )


def render_tag_page(config: Any, *, lang: str = "en", generated_at: str = "") -> str:
    """[PURE] One self-contained page for confirming what the point list means.

    Collects only. Everything it produces goes through ``iaiops tags apply``,
    which is where the refusals and the author live.
    """
    from iaiops.core.report.html import document
    from iaiops.core.runtime.config import TagRole

    t = _strings(lang)
    rows = sheet_rows(config)
    if not rows:
        body = (
            f"<h1>{escape(t['title'])}</h1>"
            f"<h2>{escape(t['empty_h'])}</h2>"
            f'<p class="empty">{escape(t["empty"])}</p>'
        )
        return document(
            title=t["title"],
            body=body,
            footer=escape(t["footer"]),
            lang=lang,
            extra_css=_EXTRA_CSS,
        )

    header = "".join(
        f"<th>{escape(t[key])}</th>"
        for key in ("endpoint", "ref", "label", "declared", "role", "running_when")
    )
    declared_running = {
        (str(getattr(target, "name", "")), _ref(tag)): " ".join(
            str(v) for v in (getattr(tag, "running_when", ()) or ())
        )
        for target in getattr(config, "targets", ()) or ()
        for tag in getattr(target, "tags", ()) or ()
    }
    table = "".join(
        _row(t, i, row, tuple(TagRole.ALL), declared_running) for i, row in enumerate(rows)
    )
    notes = "".join(f"<li>{escape(line)}</li>" for line in t["next"])
    payload = _embed(
        {
            "columns": list(SHEET_COLUMNS),
            "roles": list(TagRole.ALL),
            "rows": [dict(r) for r in rows],
        }
    )
    body = (
        f"<h1>{escape(t['title'])}</h1>"
        f'<p class="sub">{escape(t["lead"])} <span class="hint">{escape(generated_at)}</span></p>'
        f'<div class="scroll"><table><thead><tr>{header}</tr></thead>'
        f"<tbody>{table}</tbody></table></div>"
        f'<div class="actions"><button id="download" type="button">'
        f"{escape(t['download'])}</button>"
        f'<span class="hint">{escape(t["copy_h"])}</span></div>'
        '<textarea id="csv" readonly></textarea>'
        f'<h2>{escape(t["next_h"])}</h2><ul class="notes">{notes}</ul>'
    )
    return document(
        title=t["title"],
        body=body,
        footer=escape(t["footer"]),
        lang=lang,
        script=f"const SHEET = {payload};\n{_JS}",
        extra_css=_EXTRA_CSS,
    )
